const punchs = [
  "Je suis dans l’hôtel, y’a plus d’étoiles dans ma suite que dans le ciel",
  "Comme tous les gens qui ont mon taff, je me sens différent des gens qu’ont mon taff",
  "Les chansons restent éternellement, mais l’homme part en un éclair",
  "J’ai pas peur de mourir, j’ai juste peur que ma mort fasse mourir ma mère",
  "T’as l’cœur sur la main que quand t’as l’couteau sous la gorge",
  "J’prie pour qu’jamais le temps n’s’arrête parce que moi, j’ai pas l’temps de m’arrêter",
  "On a pleuré à la naissance et pour Zidane en 2006",
  "Elle est belle, mais elle kiffe trop PNL",
  "Les combattants suivent, et les baltringues se sauvent",
  "T’es jaloux parce que tu la trompes et qu’t’as peur qu’elle fasse la même chose",
  "Je suis pas riche, moi, j’suis pauvre avec de l’argent",
  "J’ai des mauvaises intentions, mais des bonnes raisons",
  "Avant je voulais construire ma vie avec mes beaux diplômes, depuis j’ai vu 8mile et je rêve d’hab...",
  "Y a la vie, ses bons côtés, moi j’suis sur l’autre berge, boy",
  "Ta langue est plus dangereuse que ta vue",
  "J’suis en écoute à la Fnac et chez les RG",
  "J’ai pris des cartons, j’ai trop tiré la vie par le maillot",
  "J’les vois comme un bon film avec une mauvaise fin",
  "J’voulais savoir pourquoi l’Afrique vit malement, du CP à la seconde ils m’parlent d’la Joconde e...",
  "Les rats ne deviennent jamais roi même quand le lion est mort",
  "Chercher le buzz, ça reste le biz’ des blaireaux… T’as dû faire deux cent mille vues la semaine o...",
  "J’ai gardé ton numéro pour pas répondre si tu m’appelles",
  "Dis-moi, qui croire si même l’espoir crois pas en lui",
  "On veut pas baiser les gos les plus putes mais boire les eaux les plus pures",
  "Pour que tout s’arrête, faudrait qu’Dieu m’arrête",
  "J’voulais cette putain d’vie, j’en paie le prix",
  "Le monde n’appartient pas à l’éboueur le plus matinal",
  "Au royaume des aveugles, l’argent règne",
  "Même sur montagne de billet j’perds pas mes vieux réflexes comme un Tuche",
  "Cherche pas à t’faire diplômer, cherche à t’faire pistonner",
  "J’pense à ceux qu’j’ai perdu quand j’vois l’étoile filante",
  "À l’échelle du temps, nos empires ne sont que des châteaux de cartes",
  "Faut-il croire en Dieu avant de croire en soi ?",
  "La vie c’est Halloween, moi j’regarde tomber les masques",
  "C’est pas en travaillant dur qu’on devient riche, en vrai… Sinon, toutes les daronnes africaines seraient millionnaires",
  "T’as pas précisé qu’t’étais une michto, t’as menti dans ta bio",
  "Pour ma part, j’considère qu’y’a des sots métiers, faire la pute sur Instagram n’est pas un taf",
  "Je constate que pour revivre faut forcément crever",
  "Je roule dans une quatre anneaux donc elle veut que je lui passe la bague au doigt",
  "Viager libre, viager occupé, c’est pas pour moi car je ferai pas ma vie agé",
  "Si j’te parle d’un gros joint, j’parle pas de plomberie",
  "Les hommes c’est comme la plomberie un jour ou l’autre ça fuit",
  "J’lui ai dit t’inquiète c’est d’la CBD, monsieur l’agent j’me drogue pas",
  "Je n’ai d’existence que dans les oreilles de ceux qui m’accordent audience",
  "Dis-moi c’que c’est l’amour quand t’es fortuné, ton « je t’aime », il sonne faux, il faut l’autotuner",
  "Tout vient à point à qui sait le prendre",
  "Ils vont te gratter, pas te regretter",
  "J’suis calibré mais j’ai pas d’uniforme (Ouh), j’baisse mon froc et tu crois aux licornes",
  "Je vois plus de chattes que Doc Gynéco",
  "Quand t’as du buzz, ils te lèchent , quand t’en as, plus ils te lâchent",
  "Elle est enceinte et c’est pas de moi. Je veux pas de l’enfant j’suis pas Joseph",
  "Plus je gagne et plus j’ai peur de perdre, plus je gagne et plus j’ai de chances de perdre",
  "Je fais mes devoirs avec madame et mes fantasmes avec maîtresse",
  "Je suis qu’une merde si ce que dit la proc’ est vrai et je pense que la réciproque est vraie",
  "Un avenir dans un chèque repas Fin du mois, tout l’monde perd du poids",
  "Quand je suis heureux, j’écoute la musique, quand je suis malheureux, je comprends les paroles",
  "Ils sont bons qu’à dire « bang-bang » dans les sons mais quand ça bang-bang vraiment, y a peu d’soldats au front",
  "Ton sourire, ça vaut de l’or, donc je creuse encore",
  "C’est pire que la peste, l’histoire se répète, et c’est peut-être bien nous le virus pour la Terre",
  "J’veux pas répandre la peur, je laisse les infos le faire",
  "Pendant que tu dors devant Netflix J’m’arrête pas, j’veux faire en une journée d’tafLe double de ton salaire net fixe",
  "Y a pas de déserteurs face au destin, tu peux essayer, c’est restreint",
  "Le temps enlève le bonheur aux enfants pour en faire des adultes",
  "Si la majorité a souvent tort, c’est que les êtres humains sont des suiveurs",
  "J’vois qu’tu stresses, t’es bloqué sur le té-cô comme le juge de ligne",
  "Faire du blé, c’est facile mais l’garder, ça c’est plus dur",
  "Y a des choses qu’on ne comprend que lorsque qu’on s’en rappelle",
  "J’ai pas gravi l’Everest, toi tu grapilles les restes, tout l’monde envie celui qui vit ses rêves",
  "J’crois en Dieu et j’ai confiance en moi, pour réussir dans la vie, c’est déjà assez",
  "J’deviens fou, j’vois des gens heureux partout, soit l’amour c’est pas pour moi, soit j’suis pas fait pour l’amour",
  "J’ai contaminé tout les nouveaux rappeurs, à moi tout seul, j’suis un « Cluster »",
  "J’m’en lave les mains si t’es au cimetière, j’respecte les gestes barrière",
  "Même si j’enlève ma cagoule, tu verras jamais mon vrai visage",
  "on n’achète rien avec des « merci » On répare rien avec des « pardon »",
  "T’oublier c’est impossible comme trouver un synonyme de synonyme",
  "Si tu veux compter de la monnaie passe moins de temps à compter tes heures",
  "Et si tu ne vois jamais mes larmes, c’est parce qu’elles coulent à l’intérieur",
  "Ce game a la tte-cha tellement large que je perds mes bagues en le fistant",
  "Des amis, j’en ai pas six cent, des options, j’en ai pas six mille",
  "Un fossé dans l’histoire nous sépare, j’ai pas monté les marches, j’les aient construites",
  "C’est devenu un commerce d’avoir un comportement de commère",
  "Mon meilleur ennemi, c’est moi-même, mon meilleur ami, c’est maman",
  "Je crois qu’à force de se chercher, on se perd",
  "La recette de toutes les victoires, beaucoup de défaites",
  "L’argent, c’est rien, le respect, c’est tout",
  "Tu cherches à être dans tous les cœurs, tu n’es même pas dans le tien",
  "J’ai fait des erreurs et j’en referai, j’espère juste ce sera pas les mêmes",
  "Ce qui compte c’est pas l’arrivée, c’est la quête",
  "Toujours en équipe, on préfère être en car qu’être en Porsche",
  "Reconnaissant je me souviens d’chaque passe, rancunier je me souviens d’chaque crasse",
  "Prendre l’argent des gens, c’est le voler, sauf quand c’est du business",
  "Je voulais être quelqu’un de bien mais j’ai échoué… alors j’essaye d’être quelqu’un de mieux",
  "J’ai l’impression que rien, c’est tout c’qu’il me reste",
  "L’argent ne fait pas le bonheur donc je veux la médaille d’or",
  "J’me confronte au mal que pour savoir si j’suis bon au fond",
  "Y’a ceux qui crient et y’a ceux qui dégainent",
  "Dès que je sens qu’elle est love de moi, j’arrête le jeu comme un boss de fin",
  "C’est quoi une star qui s’enfuit ? Une étoile filante",
  "Va dire au chauffeur que j’pose mon cul où j’veux, comme Rosa Parks",
  "Je n’vous aime pas non plus, niquez vos mères",
  "J’suis facile à trouver comme un blanc en Afrique Ou comme du sang d’immigrés sous les semelles d’un flic",
  "L’espoir fait vivre, mais ceux qui vivent d’espoir meurent de faim",
  "Le Savoir est une arme en tant de guerre, on peut tuer un révolutionnaire mais pas la révolution",
  "Moi j’suis coincé dans mon monde un peu comme Alan Parrish",
  "Blonde platine, elle fait sa Khaleesi Dragon dans la queue je l’encendre",
  "Mailler avant que les anges m’escortent, punchline profonde comme une escort",
  "Remplace tes « je » par des « nous », remplace ton nom par le mien",
  "J’m’en vais pour mieux revenir comme le fils de Marie",
  "Je crois que l’être humain il est fait d’alcool tellement qu’il m’a saoulé",
  "Ils veulent me faire reculer comme un Desert Eagle",
  "On ne voit pas ton nom comme le jour des résultats du bac",
  "Dis pas que la rue a ses raisons si la raison s’en bat les couilles",
  "J’pousse pas la fonte, je la traîne, normal",
  "Ce qui fait l’homme c’est pas l’oseille c’est la parole",
  "Nique approbation, j’traque réalisation, je vis pour légende donc y a pas de distraction",
  "J’ai beau m’approcher du ciel, mais le poids de mes pechés me ramène vers le sol",
  "Une relation ça s’entretient, dans le cas contraire ça s’entretue",
  "Ils veulent le beurre, ils veulent le buzz, ils veulent la beurette qui passe",
  "Chez nous y a de numéros 10, y a que des numéros d’écrou",
  "Faire des gros placements, des millions, ça s’fait pas qu’en étant mignon",
  "J’ai appris archi-tôt qu’la roue ne tournait qu’pour les hamsters",
  "J’doute qu’il y ait un droit chemin vu qu’la Terre est ronde",
  "Ici pour s’faire entendre faut faire une prise d’otage",
  "Si ma télé avait un trou du cul le salon serait plein d’merde",
  "Et n’oublie jamais que la critique c’est la puissance des impuissants",
  "Rentre pas dans c’game parce que y’a que les pions qui sont voués à l’échec",
  "J’me sens comme Obélix sauf que j’suis tombé dans la drogue",
  "J’ai oublié 80% de ma scolarité J’écris comme si j’ai fait la Sorbonne",
  "Les mecs sont tous les mêmes… bah, fallait pas tous les essayer",
  "Tu te prends des coups de pression, on se prend des coups de soleil",
  "Un jour, j’ai ramené deux meufs, c’était nul Ça m’a rappelé qu’j’ai du mal avec une",
  "Terroristes sexuelles, elles veulent juste se faire sauter",
  "Ma génération Game Boy sniffe plus de lignes qu’à Tetris",
  "Pas besoin d’être mathématicien pour savoir sur qui compter",
  "Si tu peux pas faire de grandes choses fait de petites choses avec grandeur",
  "C’est bien d’être le meilleur, mais c’est meilleur d’être le plus original",
  "On veut toujours changer l’monde alors qu’on devrait d’abord changer nous-mêmes",
  "T’es pas meilleur que les autres, c’est juste que tes pêchés sont différents des leurs",
  "Retiens que toutes les choses se finissent ou se finissent mal",
  "Si t’es pas occupé à naître, t’es occupé à mourir",
  "J’ai jamais eu peur des menaces, j’ai toujours peur des promesses",
  "Traite-moi de singe, ça me va bien, j’suis le plus grand des gorilles",
  "Les cojones vides mais j’ai les poches pleines",
  "Si la peur est plus forte que l’amour, dois-je la terroriser pour lui faire la cour ?",
  "Mes qualités deviennent des défauts, à défaut d’être dans les normes",
  "Malgré les tentatives, je n’arrive qu’à remplir mon casier judiciaire",
  "C’est pas la queue d’cheval qui fait la pute, c’est la partie d’jambes en l’air qui fait l’rodéo",
  "J’pense qu’à l’oseille, pas ton gros cul, j’suis du mauvais côté comme Comte Dooku",
  "Si t’as une mauvaise réponse c’est que t’as une mauvaise question.",
  "Y a pas d’étrangers, y a juste des gens qui s’connaissent pas et des gens qui s’connaissent qui sont comme des étrangers",
  "J’te trouve toujours belle mais juste moins qu’avant, les ignorants sont plus heureux que les savants",
  "Vingt mille lieues sous la mer comme si j’étais Ben Laden, Je pense pas avec le cœur moi j’pense avec la tête",
  "Crochet d’Eden, j’file à l’anglaise, weed hollandaise, Je suis le meilleur, y a pas de Hazard",
  "Besoin d’te dire que ma confiance, c’est comme les timbres, ça colle pas deux fois",
  "La vérité remonte toujours à la surface comme le p’tit Gregory",
  "Toutes les michtonneuses te l’diront, mon frère : Y a pas qu’au tabac qu’on gratte un millionnaire",
  "Le respect ne se demande pas, le respect se prend",
  "Si la richesse est dans le cœur dis toi que beaucoup m’ont ruiné",
  "J’connais les vrais, j’connais les faux, j’connais les faux qui jouent les vrais",
  "Ils sont en gamos, tout l’monde les regarde, j’arrive à pied, plus personne les voit",
  "Pas la peine de m’demander ce que je pense du rap game, moi, j’suis pas auditeur",
  "Tu nous parles de la rue mais la rue c’est ma vie Donc tu parles de ma vie, fils de pute applique-toi",
  "Les groupies sont toutes les mêmes. Les baiser, c’est baiser soi-même",
  "Et quand t’es tout en haut, les amis s’multiplient par 10, quand tu seras tout en bas, tu verras qu’il restera qu’la mif",
  "J’ai pas changé j’ai toujours été chelou T’es chelou de demander pourquoi j’suis chelou",
  "Ils voient l’album multi platiné Ils voient pas les années sacrifiées",
  "On n’avait rien, on s’promettait tout, maintenant qu’on a tout, on se fait la guerre",
  "Pour qu’tu retiennes bien, j’te dirai pas tout car moins on sait, moins on oublie",
  "On deviendra ce qu’on doit être",
  "je vis sous l’orage car j’aime quand tout est clair",
  "Je suis pas sorti du ventre de ma mère pour vendre de la merde",
  "Il m’a fallu des chaînes en or pour me rendre compte que j’suis esclave du temps",
  "L’argent n’fait pas l’bonheur, alors, j’me lève de bonne heure pour en faire",
  "J’peux donner sans même sentir que j’ai donné… Moi j’ai charbonné pour éviter de bégayer",
  "Le diable s’habille en Prada et les pointeurs s’habillent en Lacoste",
  "Je suis comme le jardinier, si ça sent l’herbe c’est que je me suis mis au travail",
  "J’arrive en silence, j’arrive en douceur, j’arrive en Tesla",
  "J’avais un cœur, aujourd’hui c’est qu’un vieux glaçon",
  "J’ai trop mal à la vie mais j’ai pas l’antidote, j’recrache ma haine derrière l’antipop",
  "Tu m’connais pas, mais pourtant tu parles de moi",
  "Mets du cash entre vous, tu verras si c’est ton poto ou c’est qu’une catin qui t’met des couteaux dans l’dos",
  "Je te laisserai le temps de me décevoir mais le temps me laissera voir",
  "Quand on fait comme tout l’monde, c’est difficile de devenir quelqu’un",
  "J’suis pas plus fort, j’suis juste plus intelligent que toi et j’aurai c’que j’veux que tu le veuilles ou non",
  "Quand t’as d’l’argent on te suit Mais quand t’es à terre on te fuit",
  "Avant, j’avais peur pour mon prochain, aujourd’hui, j’ai peur d’être le prochain",
  "Je fais du mal, j’fais du bien, j’manque de stabilité comme un poste intérimaire",
  "Les flics sont débiles, la weed est cultivée",
  "Oublie le passé, n’oublie pas la leçon",
  "Dans le creux de ma main, j’n’ai que mon cœur et mon destin",
  "Plus y a d’monde autour de moi, plus j’aime la solitude",
  "J’pourrais pas tout effacer, ses yeux m’rappellent le passé",
  "Je fais mon pain seul, j’vais les rouler dans la farine",
  "J’suis parano, je doute même de moi",
  "Tu m’aimes, je t’aime, et les autres, c’est bye, bye … quand je te trouve sur le  tom-tom, mon cœur fait « tam-tam »",
  "Toujours en vie, maman c’était ton heure, donc j’ai dû tuer l’temps",
  "On s’accroche à rien car un jour, tout s’perd",
  "Chaque jour que Dieu fait, du cash c’est ça que je fais",
  "Je me balade sans sécu’, même si tous les gars m’cherchent comme le clitoris",
  "Toujours entouré mais j’me sens toujours seul",
  "Sweat noir, jean noir, ton sur ton À l’hôtel avec deux lesbiennes dégueulasses, thon sur thon",
  "Tu peux être connu comme la lune tu feras pas d’ombre au soleil",
  "Des fois j’me dope comme un coureur cycliste, quand se réveillent mes cicatrices, j’me sens si seul et si triste",
  "Toujours la même histoire, celui qui veut t’apprendre à nager est celui qui se noie",
  "Si je m’endors, je dors 35 heures, à quel moment je vis si je taffe 35 heures",
  "Quand on me verse deux verres, même les obèses me plaisent",
  "Si un curé baise une femme fontaine ça fait peut-être de l’eau bénite ?",
  "À trop regarder derrière on oublie d’aller de l’avant",
  "Je suis tellement loin, le futur est derrière moi",
  "Si les rageux me voient marcher sur l’eau, ils diront que c’est parce que je n’sais pas nager",
  "Je lui ai dit « Passe-moi du gel », pas pour mes mains, pour t’enculer",
  "Pour aller au paradis, faut mourir mais personne n’est volontaire",
  "Pour éviter les problèmes je ne dirais plus je t’aime",
  "Aimer, j’sais plus comment faire moi J’ai perdu le mode d’emploi y a très longtemps de ça",
  "Jamais mordu la main qui m’a nourri, normal, c’était la mienne",
  "J’irai aux Restos du cœur quand ils auront deux étoiles Michelin",
  "On ira où tu voudras, quand j’aurais que ça à foutre",
  "Ils font la guerre avec des chars, on pose des carrés sur Insta’",
  "Elle m’a dit : « T’aimes mes boucles d’oreille ? » J’lui dis : « J’aime rien, j’suis Parisien »",
  "Je vais m’endormir à la morgue, m’réveiller d’une balle dans la tête",
  "Paire de larmes ne s’assèche pas mais tout ce qui brille ne s’achète pas",
  "J’donne l’argent à maman, y a qu’elle qui a le droit de tout m’prendre",
  "Elle est partie, je multiplie mes « désolé » par dix",
  "y a pas d’vrai pote, y a que des vraies putes",
  "J’aurai beau lire tout le dictionnaire, j’trouverais aucun mot pour te décrire",
  "J’préfère regretter mes discours plutôt de que regretter mes silences",
  "J’me conseille tout seul Dans ma tombe, j’serai tout seul",
  "Être mannequin sur Insta’, c’est comme être militaire sur Call Of",
  "Ma poésie vient d’en bas, elle m’tirera peut-être vers le haut",
  "J’ai toujours doigt sur ton clit’, j’crois qu’ta chatte est pute à clics",
  "Je pourrais même fourrer Martine Aubry (pute) Au p’tit-déj’ j’me fais une tartine au brie",
  "Y a pas de magie, p’tit frère dans la vie, tu deviens ceux que tu fréquentes",
  "Les verres sont servis, les filles sont sévères",
  "Ouais j’m’en rappelle, elle m’cassait les couilles, pour que j’lui brise la schnek",
  "Quand t’es pauvre, t’attends les soldes, quand t’es riche, on t’fait des prix",
  "le S",
  "Un coeur malade c’est difficile à reconnaitre, un coeur brisé c’est difficile à recoller",
  "Je préserve mon cœur j’ai que ça de précieux",
  "Elle met du rouge a lèvre mais avec ses dents jaune ça fait le drapeau de l’Espagne",
  "Quand j’étais plus jeune j’avais des rêves, maintenant j’ai des regrets",
  "J’suis taillé dans du bois d’ébène, ces rappeurs sont taillés dans du bois de Boulogne",
  "J’suis pas responsable des bouffons qui m’écoutent … Tout comme t’es pas responsable du boloss à qui tu vends",
  "Les condés collent aux fesses comme le PQ quand j’me r’lève",
  "J’attends plus l’armistice, j’attends plus la paix, nan … j’attends plus la justice, j’attends juste ma paie",
  "Rien à foutre, d’avoir un royaume si t’es pas ma reine",
  "Jugez moi ça définira pas qui je suis mais qui vous êtes",
  "Le passé, j’y peux rien, mec, mais l’avenir dépend de moi",
  "Chez eux, on ne change pas une équipe qui gagne. Chez nous, on ne change pas une équipe tout court",
  "J’aimerais t’aimer mais mon cœur cassé est inutile comme ralentir après s’être fait flashé",
  "Te fais pas tatouer l’blaze de ta femme, c’est naze car souvent le tatouage dure plus longtemps qu’le mariage",
  "Tes sentiments se prennent des murs tellement il fait noir dans les cœurs",
  "La vie c’est dur, ça fait mal dès qu’ça commence, pour ça qu’on pleure tous à la naissance",
  "Je suis devenu quelqu’un le jour où j’ai compris que j’étais personne",
  "Quand je parle de valeurs, ils m’parlent de premiers prix Ils méprisent la maîtrise, je maîtrise le mépris",
  "Les signes extérieurs de richesse cachent des preuves intérieures de pauvreté",
  "Plus le combat est dur plus la victoire est belle",
  "J’vois tout en grand comme si j’avais des jumelles, Je m’inquiète deux fois plus comme si j’avais des jumelles",
  "Je suis au pied de la montagne, je relativise, je me dis que c’est mieux qu’être au bord d’une falaise",
  "L’argent ne change pas les gens, il n’révèle que leur vrai visage",
  "La vie est comme une féministe qui twerke sur d’la trap",
  "On s’éloigne parce qu’on se dit je t’aime sans vraiment savoir ce que c’est",
  "Elle a 100ml de liquide dans la culotte, elle peut même plus prendre l’avion",
  "J’suis aimé comme ma rime, détesté comme Marine, j’vends moula pour narines",
  "J’connais des gens qui sont instruits, pourtant, ils n’ont aucune éducation",
  "J’aime pas quand c’est imposé, encore moins depuis que je suis imposable",
  "Elle veut qu’j’ouvre mon cœur, moi, faut qu’j’ouvre ma braguette",
  "Plus dur d’avoir une fille que t’aimes en face qu’une fille qui t’aime en face",
  "C’est la goutte de sperme qui fait déborder l’vase",
  "Être aimé, comme tu es, imparfait … C’est l’amour plus-que-parfait",
  "J’ai délaissé le bleu du ciel pour le blues de la nuit",
  "Si t’oublies son prénom, emmène-la au Starbucks",
  "Mes cicatrices valent le poids d’mes erreurs",
  "Ne m’prends pas pour un cougar si j’te dis qu’le premier qui m’baisera n’est même pas né",
  "J’ai d’l’amour propre mais j’aime l’amour sale",
  "Je vois plus le peloton j’ai trop d’avance, je les écoute j’entends mes flows d’avant",
  "Les codes ont changé, dans le rap désormais c’est le plus rigolo qui fait du sale",
  "Toujours le blanc qui met le noir dans le trou La vie c’est un peu comme au billard",
  "La vie, c’est comme le PQ : soit c’est plein d’merde, soit c’est tout rose",
  "J’ai des reufrés qui doivent purger des peines aussi longues que ton âge",
  "On m’a dit qu’tu rappais bien mais c’est dur à avaler comme le whisky sec",
  "Je suis blanc et j’fais plein d’argent comme la CC",
  "J’préfère laisser mes enfants dans ta gorge, plutôt qu’en garderie",
  "J’leur ai fait peur comme le futur, j’reviens sur eux comme le passé",
  "J’m’en bats les couilles que t’aies fait la Sorbonne Moi, j’ai rien fait et j’ai l’salaire de tout le personnel réuni",
  "J’vise le milliard à la fin d’ma vie, le million c’est démodé",
  "Je n’ai pas besoin d’raconter ma vie, mon silence à lui seul fait du bruit",
  "J’ai passé la bague à Tchikita, deux mois après, j’l’ai déjà quittée",
  "Si tu ken la plus bonne des plus bonnes tchoins, remercie pas son père mais le chirurgien",
  "Les MC’s tournent en rond, Si ils allaient à la vitesse de la lumière ils pourraient s’auto-enculer, les bouffons",
  "En crachant sur l’un, forcément tu suces l’autre, La salope de l’un est souvent la femme d’un autre",
  "Elle veut que j’l’épouse, j’trouve ça flippant : faut des témoins, comme dans un accident",
  "La go est douce, le négro est brut, ça va finir par coller car les opposés s’attirent",
  "Même si t’es gentil, on t’oubliera comme le premier « i » de « suicide »",
  "J’ai de l’or dans les couilles, il faut me sucer pour le croire",
  "Je cède aux plaisirs mais je n’suis pas plus heureux qu’au début",
  "Tu veux baiser pour du buzz mais j’te fais même pas la bise",
  "Toi, t’es mon frère donc j’vais pas compter",
  "J’suis dans le sale, igo, pas dans des chattes serrées",
  "Si l’amour est un crime, je suis coupable d’aimer",
  "Forcément quand tu sais qu’y a rien à perdre, tout est permis",
  "J’ai fait tout c’que j’avais à faire pour changer ma paire de Air Max en Gucci",
  "J’peux tomber pour un billet mais j’peux plus tomber amoureux",
  "Finalement, la richesse, c’est dormir tranquille",
  "Il t’a volé dix balles, mets-lui dix balles de 9 millimètres",
  "Je vis la nuit parce qu’on va tous mourir un jour",
  "J’ai le cœur sur la main et quand tu l’vois, tu m’arraches le bras jusqu’à l’épaule",
  "Te pardonner, j’ai trop d’rancœur. J’sais qu’tu recommenceras encore",
  "On avait de belles idées mais bon la vie les noie",
  "Je les aime tous, aucun ne m’aime, du coup j’veux tous les tuer",
  "Tout ça, c’est fini, viens, on fait la paix Tu m’aimes à l’infini, j’ai lu dans ta tête",
  "J’vends la moula couleur Homer, ma daronne mange toujours pas de homard",
  "Rien n’a changé à part le change, j’demande un temps mort, c’est malheureux je reviens c’est dangereux",
  "Cherche pas les clés d’mon cœur, j’ai que les clés d’la Lambo",
  "Ne fais pas trop de bien ou tu seras cloué sur une croix",
  "Seine Zoo, le French OVO, voilà nos vies en VO, voyages en avion, beaucoup d’envieux, on protège nos vieux",
  "Prudence est mère de sûreté… Sûreté, ta mère la pute !",
  "J’suis comme Broly, j’deviens paro dès qu’ça parle de carotte",
  "Le passé fut turbulent et nous réserve un futur brûlant",
  "Un regard, un mytho, un sourire, et le cœur qui n’veut plus se nourrir",
  "Pas changé, toujours pas d’amis, ceux qui manquent sont déjà partis",
  "J’aime pas tes rêves, cauchemars entassés, le cœur qui brûle, sentiments glacés",
  "Celui que tu suces il me suce tous les jours",
  "Je te rappelle si je m’rappelle qu’il faut l’faire, c’est la paix ce soir faut une autre guerre",
  "Triste est la surface, sombre est l’intérieur, vivre les cauchemars, les rêves restent inférieurs",
  "Donne-moi ton cœur, dis-moi tout, qui t’a fait du mal avant ?",
  "Y’a que deux places dans le féfé, quand tu perces, t’as moins d’amis",
  "Rappelle-toi l’époque où j’découpais les plaquettes comme les corps dans Grey’s Anatomy",
  "Tu bloques sur les défauts des autres, et c’est ton pire défaut",
  "Y’a des combats qu’tu peux pas gagner",
  "Fermez vos gueules, j’ai gagné mes procès, mes textes étaient mieux quand l’juge les posait",
  "J’voudrais être naïf, plus croire mon cœur que mes yeux",
  "Un jour, ton pote traîne qu’avec ses collègues de taf, pourtant, c’est l’genre de connards que vous détestiez en classe",
  "J’veux plus jamais nier les évidences, j’sais qu’il va falloir prendre mes distances",
  "Mon cœur est tout nu, j’ai plus rien à m’mettre, je t’aime sans strass et paillettes",
  "Pour niquer mon moral, elles se sont fait toutes belles, les bonnes et les mauvaises nouvelles",
  "Les souvenirs et le vécu remplissent la poubelle",
  "J’suis dev’nu riche, j’vais racheter ton âme au Diable",
  "J’tourne en rond, au rond-point Victoire, j’suis bien loin des vaincus",
  "Je suis un pacifiste quiconque me défie repose en paix",
  "Le plus dur c’est d’parler d’futur quand ton destin a été tracé par un manchot",
  "J’fais semblant d’t’écouter comme les freestyles au phone-tel pendant les Planète Rap",
  "J’avais pas d’autre choix que d’prendre ça à coeur, j’suis un boss, mes haters font plus de 35 heures, pas de pause",
  "Sans ton reflet dans mes yeux ma vie ne ressemble à rien",
  "J’entends des cris dehors, j’entends des cris dedans",
  "Inouï comme un inuit sur la ligne 8",
  "L’enfer est gelé, le paradis crame",
  "Les jolies filles à la piscine se croient toutes au Club Med, mais les 20 centimètres que t’as pris c’était pas au Subway",
  "Tout c’qui est bon est illégal, alors j’commence à croire, que si l’amour c’était si bien, ça s’rait interdit par la loi",
  "Que Dieu vous pardonne parce que moi j’le f’rai pas",
  "Les profs de maths à Nazareth n’enseignent pas les produits en croix",
  "Et lui, en face il fait des grands sourires pour mieux s’refaire sur ma nuque, t’as capté l’truc ?",
  "Tu devrais faire les comptes de ta vie, ça dépassera pas les poches de ta veste",
  "Il y’en a combien qui m’aiment qu’est-ce que j’m’en bats les couilles, gros, au final, même moi j’me déteste",
  "J’ai besoin de toi, pour me sortir de là, sous-estimé, comme un billet froissé",
  "J’suis l’incendie, t’es l’feu d’briquet",
  "P’tit frère, la cité ça pue la merde, suis pas les deux numéros qui t’abritent",
  "Mais quand j’achète, ça fait bosser les p’tits ; le légaliser, ça ferait chômer les flics",
  "On n’arrête pas frère, on continue avec moins d’amis",
  "Une fille bien dans la maison close, une pute dans la Maison Blanche, Mélania !",
  "Elle s’étonne de voir le cœur de la bête, y’a de la tendresse caché sous les crocs de l’homme",
  "Trop peu de gens savent vivre vraiment, suis-nous si tu veux voir le vrai monde",
  "Ouais tu sais tout nous oppose mais, très différents on l’sait, j’crois qu’à force de s’chercher, on s’perd",
  "J’baisse les vitres regarde les gens, j’recompte le biff elle ouvre les jambes",
  "Ta meuf a mis l’cadena sur Insta, j’crois qu’j’ai fais sauté la serrure",
  "J’veux être ivre, demain ne compte pas, pourquoi la vie devrait être un combat ?",
  "J’me souviens des rires, j’me souviens plus de toi",
  "Quand je blackout, c’est chiant ; pardonne-moi si j’tais méchant",
  "Vas-y, moi aussi, j’vais louer la Tour Eiffel, j’crie « V. A. L. » partout comme si j »tais DZ",
  "J’arrive sur eux comme un missile, m’auto-détruire, c’est un plaisir",
  "Je multiplie les p’tits pains, je n’l’appelle pas, j’sais qu’il vient",
  "J’t’écoute, je fais l’effort déjà d’ouvrir les yeux, comprendre, c’est d’mon ressort, pardonner celui de Dieu",
  "On n’dit pas toujours ce que l’on le fait, mais on fait toujours ce que l’on dit",
  "J’dirais que la vie est une grosse chienne et qu’il ne faut pas être en chien pour la dresser",
  "Et les derniers seront les premiers quand ils pourront tricher",
  "Viens j’t’emmène avec moi, la nuit j’ai rêvé que d’ça, construire une villa à Kinshasa",
  "Dis-moi si tu m’aimes, dis-moi si tu n’aimes plus, que j’te raye de ma vie",
  "Avoir la conscience du plaisir, c’est bien, avoir l’inconscience de souffrir, c’est mieux",
  "Moi j’ai connu des gens que j’ai voulu flinguer, j’ai pas d’flingue mais j’peux trouver un couteau",
  "On joue quand la nuit tombe, fier jusqu’au SAMU, rien de plus bête que le danger, mais faut bien qu’on s’amuse",
  "La misère, ça impressionne moins qu’un salto, ça les ennuie comme le goût de l’eau plate",
  "Chaque jour une nouvelle cascade, j’aurais du demander une doublure",
  "Sans pitié comme l’amitié, incontesté, rap au Subutex et c’est comme ça quand on a gesté, les faux parlent des faux",
  "Souhaite-nous santé, bonheur, le reste on l’achètera",
  "Si j’tue un fils de pute, y a pas mort d’homme. Le drapeau est noir car l’blanc est pour ceux qui abandonnent",
  "Tout c’que j’voulais, c’était fuir la routine mais c’est devenu la routine",
  "J’passe mes journées dans mon lit, Jésus pourrait pas m’lever",
  "Rappelle-toi qui tu snobais quand tu montais, c’est les mêmes que tu croiseras dans la descente",
  "Si vous n’avez pas peur du vide, regardez Murielle dans les yeux",
  "Je t’aime, salope, tu m’attires, j’ai toujours doigt sur ton clit’, j’crois qu’ta chatte est pute à clics",
  "Maintenant dans les soirées mondaines, tout l’monde aime Doums",
  "On baisera à deux sur un quatre places, bâton dur comme un Kapla",
  "J’dis la vérité, comme un enfant, ça rend pas vraiment heureux mais ça défoule",
  "J’demande encore si y’a de la meuf, ça fait pitié, comme si j’avais encore dix-sept piges",
  "J’ai cherché la réponse en fixant le plafond jusqu’à cinq heures, le genre de problème qui casse un cœur",
  "Une centaine de tours de soleil ça passe vite, hein mon vieux ?",
  "Ça devient dangereux quand t’as plus de pouvoir que de tentations",
  "J’avais des rêves immenses mais c’est quand on retombe qu’on saigne",
  "Je voulais qu’on trinque ensemble à la vie impossible qu’on aurait eu",
  "Mes ennemis vident leurs chargeurs mais ça me passe au-dessus comme Néo",
  "Si tu poses des bombes pour Dieu, j’préfère pas savoir c’que tu peux poser pour Satan",
  "On a trop de clichés sur les gens, même avec une équerre on verrait les choses du mauvais angle",
  "Je peux juste te l’assurer, j’regrette pas mes erreurs, j’peux juste les assumer",
  "Elle me dit qu’elle aime voyager pour sentir les choses que l’œil humain ne voit pas",
  "Le teint pâle et l’âme noire, l’horizon grisonnant",
  "Aucun rapport protégé, pour faire la fête, faut des g, ton mélange est trop léger, tu m’as pris pour un gros pédé",
  "On dira quoi aux gosses ? Qu’on a bien essayé ? Nan, faudra pas bégayer",
  "Lorsque l’on m’adore, je m’enfuis, c’est pour ça qu’je fixe le plafond",
  "Arrête tes conneries, éteins ta télé, tu vas finir par croire leurs balivernes",
  "On efface tout quand je crache, j’ai trempé ma bite dans un pot d’Tipp-Ex",
  "J’élève la voix que sur Pro Tools, si tu m’saoules trop, on en restera là",
  "J’peux plus me voir, seul, je me lasse, j’vais m’suicider, je me menace",
  "J’crache du souffre et vomis du pétrole ; l’industrie voudrait m’forer, ça m’désole",
  "Là, j’me branle à mort en attendant la mort, devant l’amour de ceux qui n’font qu’un corps",
  "Ouais, le sexe et l’argent, ça fait tout, j’ai les deux et pourtant, ça fait rien",
  "L’évolution n’aura fait qu’un tour : alcool et shit et on redevient des singes",
  "À force de l’lire, j’finis par croire qu’à force de l’dire, j’finis par l’être",
  "Mes nuits sont blanches, mes idées noires",
  "Si tu rentres, prends ton ticket d’vestiaire en photo",
  "J’me suis perdu comme les lettres de Stan",
  "J’en connais qui mériteraient d’aller en prison, pire, j’en connais qui mériteraient que j’aille en prison",
  "L’enfer c’est les autres, sauf que sans les autres t’es encore plus mal",
  "Ton père aime critiquer les Roms, mais tes robes viennent de chez Manoush",
  "J’ai dit : « Je t’aime » à des connasses qui n’en valaient pas la peine, j’ai jamais dit : « Je t’aime » à ma mère",
  "J’fais comme le père de Bernie : j’encule tout",
  "Roi dans l’mensonge, esclave dans l’vrai monde",
  "Promets-moi de ne pas de me rejoindre en enfer, et si t’essayes pourvu que les anges te gardent",
  "Dois-je en vouloir à Dieu ou bien l’remercier d’être en vie ?",
  "Fumer ça créé des connexions mais ça m’fait poser trop d’questions, c’est pour ça que j’ai besoin de boire en même temps",
  "C’est qu’une mise en abyme de mes péchés morts mais sans décès",
  "Ta meuf a un anneau dans le ventre, je l’ai doigtée au point que j’en suis passé entre, autrement dit nous sommes fiancés",
  "Tout peut s’arrêter, les deux barres parallèles sont des carrés dans la réalité",
  "J’étais l’dernier à faire le premier pas",
  "J’suis incapable de nous voir ensemble, mon cœur est myope de souche",
  "J’serais ton Monk, tu s’ras ma Trudy, j’l’ai pas mariée pourtant elle crie « oui »",
  "Ah, ce monde c’est une bonne blague, je lis les nouvelles pour me faire les abdos",
  "Qui va apaiser nos maux ? J’ai vu la peur apparaître dans les yeux des gens normaux",
  "On se déteste tellement qu’on refait l‘amour, parce que c‘est comme de la drogue on a de quoi planer",
  "Je voulais plus d’air, plus de distance, j’en ai juste un peu trop mis",
  "Pourquoi c’est toujours quand faut profiter du présent que j’ai des absences ?",
  "On a droit à une autre chance, mais pas pour la même erreur",
  "Demain me parait bien mais demain me parait loin, comment aimer un cœur en acier valyrien ?",
  "J’suis insomniaque, mon seul rêve c’est d’pouvoir rêver",
  "J’pleure celui qui meurt jeune mais encore plus celui qui meurt triste",
  "Ok, j’suis sûr qu’les animaux méprisent les Hommes: Comme la sclérose en plaques, j’aimerais détruire les os",
  "J’sais très bien que je n’ferai aucun cambriolage mais j’ai des valeurs que je n’céderai pour aucun prix aux lâches",
  "Nos couilles, nos poches et nos têtes se vident au cours de la semaine comme le Parlement",
  "Dites-leur qu’au début j’avais aucun talent, 7 ans plus tard j’ai plus aucun talon… d’Achille",
  "Intelligent sombre, tout le monde se tait quand l’or parle",
  "J’veux un monde avec que des miroirs, une radio qui passe que ma musique",
  "La vie est une imparfaite perfection",
  "Est-ce que tu gardais, à l’époque, des secrets d’famille lourds dont tu peux même pas parler à tes potes ?",
  "C’est malheureux, j’suis jamais l’même à part quand je baise, j’suis malheureux, je sais qu’elle m’aime même quand je tej",
  "Arrêtez d’imprimer les notices, nous n’les lisons pas",
  "J’ai vis-à-vis sur l’enfer, j’vis ma vie sans m’en faire, j’sais qu’la suite c’est l’Eden",
  "Je suis toi, tu es moi, je sors même de ta mère",
  "Pourquoi ça te fait plus de bien quand t’as mal ?",
  "Pour l’unité, faut des ennemis communs",
  "On dira dans la presse que c’est à cause de la hess, qu’on était des sauvages, des otages du naufrage",
  "C’est quoi l’pouvoir quand l’Président, c’est la plus grande salope du pays ?",
  "J’vais faire l’million sans chignon et sans serre-tête",
  "Je vois les lumières de ma ville, je vois les jeux d’ombres. Je suis comme la nuit : chaque jour, je tombe",
  "Hommage aux p’tites graines qui traînent dès le début du soir",
  "Tu veux des vrais ? Viens dans le studio, y’a que ça, mon passeport est couvert d’encre comme le dos d’un Yakuza",
  "La mort avant le déshonneur",
  "J’te comprends pas mais j’ai tes yeux pour sous-titrer. Tu m’as dis qu’un jour on se lierai qu’une nuit on se quitterait",
  "Je sais qu’on serait même pas heureux ensemble, nous sommes de ceux que la rancune sépare",
  "L’amour est mort en bas, ils m’auront pas",
  "Tu n’sais pas encore l’enfer qui t’attend, le regard des uns, le rejet des autres",
  "Possédé par des entités qui vibrent très bas ; mes anges, mes démons qui s’embrouillent : j’peux pas suivre le débat",
  "Qu’est-c’qu’ils vont faire ? Me briser le cœur ? C’est bon, y’a rien dedans",
  "J’leur fais du mal, pourtant, elles r’viennent, parce que j’leur fais trop de bien quand j’entertain",
  "On s’écarte des anges c’est mieux, faudrait pas qu’ils s’brûlent les ailes",
  "Sous alcool, sous beuh, j’ai tout fait consciemment",
  "Docteur, soignez mon hémorragie que j’me fasse plus d’mauvais sang",
  "Tous les jours c’est la même : du chagrin et d’la peine, mes problèmes me rappellent qu’mon sourire n’est pas vrai",
  "D’t’façon, même quand j’veux donner d’l’amour, elle est prise de spasmes",
  "J’peux continuer à sourire, faire semblant qu’c’est l’paradise",
  "Des figures s’enchaînent mais des souvenirs m’enchaînent",
  "Et même quand mon cœur saignait, mes yeux eux, ne pleuraient pas",
  "A miser sur une femme j’aurai du miser sur ma mère",
  "A chaque fois que j’aime quelqu’un mon coeur viens braquer ma fierté.",
  "Si mes désirs changent, faudrait quand même qu’un jour, j’arrive à bien m’aimer",
  "J’roule un pilon, j’pète une canette, comme Jul, j’parle des détails, j’fais pas l’fou",
  "J’me rapprocherai de l’enfer pour éloigner les démons de la nouvelle villa",
  "Le présent m’chuchote : « Poto tu vas souffrir », donc mes enfants j’leur mentirai que j’suis heureux",
  "J’lui mets la fessée comme si j’étais son père, les yeux sont vides mais les poches sont pleines",
  "Deviens génial, fais-les t’envier, fais-les t’regarder, fais-les trembler, fais-les rêver",
  "Ils écoutent le JT mais n’veulent pas croire à la magie",
  "Et on m’avait dit de bien choisir mes amis, mais j’ai choisi les mauvais",
  "Ton sourire, ça vaut de l’or, donc je creuse encore, j’ai tellement mal mais je fais comme si je ne voyais rien",
  "J’suis dans l’hôtel, y’a plus d’étoiles dans ma suite que dans le ciel",
  "J’les vois faire semblant d’être content pour moi, tout en se demandant combien ça touche par mois",
  "Et quand les glocks touchent les mentons, les langues se délient",
  "J’ai promis d’être le premier, quitte à tricher pour gagner",
  "Vis ma vie en 4K, vis ta vie en 240p",
  "On n’a pas rempli les pochons ensemble, on n’a pas d’lien de parenté",
  "À c’qu’il paraît, j’ai des yeux que pour toi, chacun d’mes textes, chacun d’mes regards, tout c’que j’fais, c’est pour toi",
  "Les meufs, c’est des soucis, on a trop d’préjugés, on est tombés que sur des **** qui à quinze ans savaient sucer",
  "Est-ce que toi tu m’aimera toda la vida ? Quand les verres et l’compte en banque seront vides",
  "Et quand les planètes sont alignées, j’repète un gros doré, j’suis conscient qu’la rue m’a eu",
  "On répond pas sur Twitter, on vient t’chercher directement chez ta tiper",
  "Quelle idée d’aimer une femme a l’humeur vengeresse ?",
  "J’en connais un rayon, je raconte pas de disquettes Elle a mordu l’oreiller comme si c’était un cheesecake",
  "« T’es trop vulgaire, tu seras censuré Damso » : deux flows plus tard, premier son passe en radio",
  "Ma douce me connait mieux qu’tout le monde, m’a soutenu dans moments de gloire et de peine",
  "J’vais te cramer au monde entier, grillé, j’vais te Serge Aurier",
  "Le cœur sur une plaque allumée j’écoute Agnès Obel",
  "J’écris ces lignes en espérant qu’tu n’prennes pas la peine capitale au jugement dernier",
  "J’ai vu la haine, avec une Black Card, péter les plombs, j’ai vu l’amour avec une carte Electron",
  "Le cœur en chaleur, je n’sais pas si je suis triste dans mon bonheur, ou heureux dans mon malheur",
  "Tu me diras non quand j’te demanderai si tu m’aimes, et c’est un « non » bien plus précieux qu’un « oui »",
  "La vie c’est dur mais, ici on s’en remet, plus rien ne m’étonne jusqu’ici tout va bien",
  "Plus j’connais les Hommes, plus j’aime mon rot’; ta provenance, appartenance, on s’en moque",
  "Je regarde le ciel, le soleil caresse mon âme",
  "J’crois plus au coup d’foudre car il ramène l’orage",
  "La seule question que je me pose : pour qui ça vaut la peine de souffrir ?",
  "Ce qui fait le plus mal c’est pas les attaques de ses ennemis mais le silence de ses amis",
  "J’sais pas pourquoi on parle du coeur, vu que moi je ressens tout dans le ventre, quand tu tournes dans le vent",
  "La seule personne qui crie mon nom c’est mon père quand j’suis bourré",
  "Quand j’disais : « C’est nous, l’futur », j’parlais d’maintenant, j’parlais d’cet instant, le futur, c’est maintenant",
  "Toujours dans l’œil du cyclone comme Sergio Busquets",
  "On a cette foutue faculté qui fait qu’on s’bonifie avec le temps ou qu’on fane",
  "J’me tourne tellement les pouces que j’vous bats tous au bras de fer chinois",
  "Qui aura l’sourire en coin d’bouche si je flanche ? Ceux qui parlent fort sont que des baltringues déguisées",
  "Tente ta chance quand tout l’monde abandonne. Là pour ger-chan la donne, le reste on s’en balance",
  "J’me sens d’humeur ironique comme un gros porc en survet",
  "La vie c’est une brasse : Tu peux sonder les abysses ou nager en surface",
  "T’as l’nez dans la che-blan comme si la vie n’était pas assez speed",
  "En rimant je l’ai fait, pas eu besoin de la Tour de Babel pour toucher le ciel",
  "Je l’ai doigté, tu n’la pointes que du doigt",
  "Mais comme tout salaud, j’t’ai téléphoné, j’t’ai récupéré, puis j’t’ai fait pleurer parce que j’en ai rien à foutre",
  "C’est quand les gens partent que les gens regrettent",
  "La vie c’est le patin, j’suis la patinoire",
  "Quand je suis avec toi, j’oublie tout c’qui va mal, j’aimerais t’ouvrir mon cœur, en douala, lingala",
  "Vous prenez pas pour Moïse, on a dit pas les mères",
  "Faut que je trouve Dieu avant qu’il me trouve",
  "J’fais des millions, on verra plus tard pour l’amour",
  "J’suis pas eux, t’es pas elle, ils sont pas nous",
  "Quand la lumière s’éteint, j’sais plus qui sont les miens. À qui donner de l’amour ? À qui donner du sien?",
  "Certains disent que la vie coûte cher, et moi j’dis qu’elle n’a pas d’prix",
  "On a peur de Dieu, t’as peur de perdre tes followers",
  "J’suis parti avant l’aube, la tête remplie d’espoir, les poches dépourvues d’euros",
  "Suffit qu’Instagram disparaisse pour que tout l’monde t’oublie",
  "La France ne m’écoute pas, elle m’prend pour un X-Men, parce que j’suis jeune, libre et coupable",
  "Si j’avais plus d’euros, j’t’offrirais plus que des mots, si j’avais plus d’euros, on irait vivre loin des autres",
  "Maintenant j’me tourne vers toi afin d’exaucer mes vœux, car, quand le ciel est noir, les étoiles sont dans tes yeux",
  "Les keufs cherchent des arabes, f’raient un perfect en vidant la Seine",
  "Tu voulais l’infini ? Imagine le numéro d’série d’une balle",
  "Des sourires en coin, des clins d’oeils, avant le deuil d’un amour en déclin",
  "Notre couple succombe à ce désir puissant puis s’ennuie, et le désir disparaît en même temps que la possession",
  "On traite nos corps comme des déchetteries : Consomme la mort en s’disant qu’on va pas s’empêcher d’vivre",
  "J’irai sûrement au paradis parce que l’enfer j’y suis déjà",
  "J’essaie d’changer, d’m’adapter, mais j’suis habité par la quatorzième lettre de l’alphabet",
  "Rien d’plus hypocrite que le regret",
  "Mystérieux comme la mort de Tupac et de sa feumeu Aaliyah",
  "Une écriture remplie de haine, la cabeza remplie de rêves",
  "Et lève toi tôt si tu veux bosser, j’l’ai promis à mes proches, j’peux pas foirer les projets, c’est pour ça que j’m’isole",
  "Tu voulais plus t’poser, t’avais tout fait pour t’aguerrir beauté, mais moi j’ai tout fait pour t’acquérir",
  "Dès le réveil avec des schémas scientifiques ; la vie : un débat sans limite",
  "Les politiques nous traitent de paresseux mais leurs postes sont fictifs",
  "T’es mieux sur les photos comme un foodporn",
  "Un pansement sur les lèvres quand mes yeux aux cieux s’élèvent",
  "Le silence fait plus mal que les mots, chez nous l’espoir c’est l’argent des pauvres",
  "J’ai des trous d’mémoire, j’ai des trous d’mémoire, qu’est-c’que ça fait d’être heureux ?",
  "J’ai de l’amour que pour très peu de gens, car il ne m’reste que très peu de temps",
  "Séparé dans l’bien, unis dans l’mal, tu t’rends compte, on n’a pas l’même Dieu mais on a l’même Diable",
  "Si tu savais comme j’te déteste, tu saurais à quel point j’t’aime",
  "Crois-en mon expérience, issu d’un peuple averti, c’est B2O, j’ai 423 ans",
  "J’t’explique la scène, qui veut ma peau perdra la sienne, kho, froids sont les repas dans nos assiettes",
  "Fatigué, dur de m’faire à l’idée qu’faudrait qu’j’te tourne le dos pour que nos deux cœurs soient alignés",
  "J’repousse l’heure de dormir, mes rêves pourraient régler mes problèmes trop vite",
  "Le plat s’mange froid si y’a l’temps d’attendre",
  "Petit, les gens sur les bancs allongés dans les squares, attendent l’arrivée d’un amour dont l’avion a pris du retard",
  "Laisse-moi tout t’expliquer : le problème, c’est la peur, quand j’m’enfonce dans la nuit, j’cherche la lumière ailleurs",
  "À toutes ces générations mariées trop tôt, qui m’donnent espoir quand j’vois les couples vieillir ensemble sur les photos",
  "J’fais rien à fond donc j’serai qu’à moitié triste",
  "J’viens pas du ghetto, je n’viens pas des cités, donc si j’dois te niquer, j’le ferai seul tout",
  "J’paye une tepu j’évite ainsi resto et cinéma",
  "Si je peux le faire, t’en es capable; nan, je ne suis pas un mec à part",
  "Depuis les chaînes et les bateaux j’rame, t’inquiète, aucune marque dans le dos man, j’les ai dans le crâne",
  "La mort c’est la sœur de la paresse",
  "Depuis 0.9, ils critiquaient mais ont tous saigné l’autotune",
  "Même sourire, différentes blessures, même compte, différents montants",
  "Même si j’ai plein d’potos, je sais que sous terre je s’rai tout seul",
  "J’préfère un loup solitaire plutôt qu’un mouton populaire",
  "On a grandi comme des hommes, on porte nos couilles jusqu’au décès",
  "Tu connais nos récits, on était trop rêveurs, très loin des paresseux, matrixé par les sous mais bon j’avais raison",
  "J’ai grandi, j’ai muri, j’ai compris que la confiance n’est pas une garantie",
  "Jésus dit de tendre la joue mais je n’suis pas pratiquant",
  "J’ai craché sur ton sol, j’n’y mettrai jamais l’genou",
  "Je veux qu’ils vivent leurs rêves, pour ça je serai blindé",
  "Je suis à 91 mille lieues sous la merde",
  "J’veux jamais t’faire de mal pourtant, j’le fais quand même, c’est comme ça, j’finis toujours par détruire c’que j’aime",
  "Le type est tellement homophobe il caresse pas son chien",
  "Un jour, on est venus au monde, depuis, on attend qu’le monde vienne à nous",
  "J’me construis plus dans le regard des autres, j’suis ni des leurs, ni des vôtres, ni des nôtres",
  "Derrière moi beaucoup de traitres, j’ai le dos couché sur des flèches",
  "On doit être bêtes, ouais, p’t-être, mais ma plume peut clouer l’bec de Houellebecq",
  "J’ai un cœur tombé du camion, le sourire au bout du canon",
  "À l’école de la rue j’ai fait Harvard",
  "Ton cercueil ton nouvel habitat, je n’viendrai pas à ta crémaillère",
  "Si l’amour rend aveugle, les problèmes rendent la vue",
  "Mais l’amour, c’est quoi quand le mariage est la cause principale du divorce ?",
  "Souvent la vie m’a fait du mal, j’l’aime autant que j’la hait",
  "On prend pas le temps de donner du temps à ceux qu’on prétend pourtant, aimer tant",
  "Le savoir-vivre n’est pas d’la politesse, mais de la politique pour prendre l’avis des gens",
  "C’est quoi un souvenir quand t’es le seul qui s’en souvient ?",
  "Ils veulent relancer l’économie, désastre écologique, pardonnez moi d’être plus émotif que logique",
  "Y a qu’la douleur qui ne ment pas quand tout le reste n’est que mensonge",
  "Conscient des enfers, la vengeance est un plat que j’mange ap",
  "Pé-sa en noir avec une faux, je contourne les MC’s à la craie blanche",
  "Quand la roue tourne que je t’encule, j’appelle ça le Karmasutra",
  "On trinque à nos balafres, à nos crochets tous les soirs",
  "Donne-moi ton cœur que j’écrase mon mégot, c’est à toi que je parle donc fais pas ton De Niro",
  "Comment puis-je prouver ce que je vaux, si leurs valeurs ne me correspondent pas",
  "J’me retourne dans mon lit en m’demandant si j’dois les baiser Vu qu’la nuit porte conseil, j’me lève avec le barreau",
  "Le cœur veut rien savoir, alors on le supplie, l’amour on n’le fait pas, l’amour on le subit",
  "Même avec les cordes vocales coupées, je serai un mec de parole",
  "On l’a fait tout seul, du sous-sol au toit sans boussole, de la caresse au doigt dans l’boule",
  "J’ai moins de copains que de copines, le monde est à nous d’après Tony",
  "J’perds mes mots je repense à ma vie, est-ce je fais le bon choix ?",
  "J’ai cette particularité : aucune confiance envers les femmes",
  "Les âmes de taisent, les actes se font",
  "J’ai toujours le mauvais rôle mais je joue que les meilleurs films",
  "J’ai creusé tunnel dans son cœur, j’me suis évadé",
  "Mon initiale sur ma bague puis sur ta joue, parce que t’es naze et tu perces et tu t’la joues",
  "D’où sors-tu ? Ta douceur tue. Mais, mais, mais d’où sors-tu ta douceur ? Il y a plus d’un homme qui tuerait pour toi",
  "L’amitié et l’amour peuvent affaiblir un homme",
  "J’crois plus en l’homme parce que j’crois plus en moi. Je suis un homme complètement irrécupérable",
  "Vroum, vroum, j’fais des roues arrières dans l’cul d’ta madre, on peut même pas dire qu’t’as mal joué, car t’as pas joué",
  "Première contre-attaque, je marque, je marque comme Landers, Landers, j’ai le sourire d’Hisoka dans Hunter × Hunter",
  "Avant d’avoir le respect, essaye d’avoir le mental",
  "Si j’ferme les yeux quel est l’frère qui m’le donne ?",
  "Face à ma solitude, je tourne le dos à l’univers, je veux faire le bien, ça embête Lucifer",
  "Le mal pour les biens, l’enfer pour le paradis",
  "L’avenir des miens au péril du tien, j’dois sortir le monstre",
  "J’étais pas initié quand j’ai vu des amis quitter le monde, la rapidité de l’ombre peut parfois limiter le soleil",
  "Je n’sais pas pourquoi les hommes détruisent tout ce qu’ils veulent s’approprier",
  "Obliger de vivre dans cette société, mais je ne veux pas de leçons venant d’elle",
  "T’empêcheras jamais les gens d’parler",
  "Les choses sont souvent plus belles avant, comme le visage de Bardot Brigitte",
  "Plus b’soin de combler mes besoins, depuis qu’femme et enfant, j’entretiens",
  "J’suis dans sa schnek, t’es dans sa friendzone, tu l’as jamais tiré sauf au paintball",
  "Te confie pas à toutes les gos, souvent, c’est perte de temps, fais des études et fais des loves",
  "Jamais voulu être blessant, maladroit comme à la naissance, présent mais l’esprit est absent",
  "Ce soir, je regarde vers le ciel, j’fume, j’m’enfonce dans l’siège. Le quartier, c’est fade, l’argent rajoutera l’sel",
  "T’es bonne en cuisine, t’es bonne en legging, j’suis né dans les grands vins, t’es mort dans les vignes",
  "Quand ta bonne étoile est pudique, un ciel noir, une larme qui nettoie les pupilles",
  "On pleure ceux dans l’au-delà, mais les morts ne versent pas de larmes",
  "J’ai couronne sur la tête pourtant c’est le voisin qui a eu la fève",
  "Majeur en l’air, sans commentaire, elle m’tournait le dos, j’ai tourné la page",
  "On passait du temps à essayer d’en passer",
  "L’avenir bloqué dans des espérances inespérées, si c’est pas moi qui l’fait je sais qu’personne va m’aider",
  "Les hyènes ressentent la tumeur, et moi je suis d’humeur palestinienne",
  "Ma longévité dans ce game en dit long, ta carrière en nylon, mes seules barrières sont de corail, j’suis un Benzema à Lyon",
  "Je me dis qu’il faut qu’on veille les uns sur les autres, pendant que mes amis dorment autour de moi",
  "Au pays du bleu blanc rouge j’arrive en noir c’est un handicap",
  "Issu d’une jeunesse qui m’choque, attiré par le crime, genre, si j’me flingue en live, combien de screenshots ?",
  "Parce que chez moi le cœur est froid d’puis l’œsophage",
  "J’vis la vie que j’aurai pas",
  "La pauvreté, ma seule phobie, faire de la maille, mon seul hobbie",
  "Je les ai vue partir quand j’ai dis aide-moi, je sais qui m’aime, qui ne m’aime pas",
  "Les vérités sont compliquées, les clichés sont stables",
  "Pourquoi les gens sont plus agressifs en voiture ? Quand ils s’sentent en sécurité, ça fait sortir leur vraie nature",
  "La nuit j’fume et j’nous revois : T’es mon plus beau cauchemar",
  "Un autre fréro à terre, un sourire vient de partir",
  "Tu veux vraiment réussir ? Faut y aller, on veut devenir boss, fuck être salarié",
  "Ta pétasse a sa robe de mariée sur son profil Tinder",
  "Vos rêves sont mes cauchemars",
  "Dans la banlieue c’est l’Moyen-âge, y’a pas d’maille et sur l’droit chemin y’a un péage",
  "Si tu cherches l’échec, tu demandes à Kaaris",
  "J’ai fait du game une dictature, pour ça qu’on me récompense pas",
  "Né dans les ronces, le cœur égratigné",
  "Mon Jardin d’Eden ne dépasse pas le matelas",
  "Tout niquer tout niquer comme Gargamel j’ai un rêve bleu très particulier",
  "Avant que Lucifer ne me crucifie, je me suis laissé faire et j’ai cru ses fils",
  "Est-ce que tu t’es déjà senti vivre ou est-ce que t’essayes d’te persuader ?",
  "Les ennemis attaquent par devant, donc j’surveille les amis de près",
  "Faut qu’tu saches j’aurais pu devenir pire qu’eux, à une épine près du cœur, à un tir d’la panique, à un tir d’la panique",
  "J’kiffe voir la misère s’élever, j’me suis fatigué à rêver, j’me repose sur les faits, ouais bientôt j’me refais",
  "Toute l’année je les aime, j’rêve d’un avenir heureux pour eux, car au fond sourire nous va à merveille",
  "Joue pas le chaud si tu refroidis devant la braise",
  "J’aimerais un gosse mais à laquelle de ces putains le faire",
  "Derrière lunettes opaques, les yeux rouges, presque aux larmes, je contemple mon futur, crache sur passé trop cramé",
  "Je me suis toujours promis de tout baiser, réussir direct, pas de coup d’essai",
  "J’veux rester vrai comme JUL",
  "Plus d’vacances, pas d’été, que du taff, on dormira quand on s’ra décédé",
  "Toutes les montres donnent la même heure, je m’en bats les couilles, j’veux une Audemars",
  "Chily chute dans le clip de Koba LaD",
  "C’est là que j’ai su qu’un ami qui ne l’est plus ne l’a jamais été",
  "S’ils aident les jeunes, c’est à devenir des vieux comme eux",
  "Shay nue .. la requête super recherchée sur Google",
  "Sentiments égarés, on sourit pour ne pas pleurer",
  "Faut jamais céder à la pression du groupe, toute façon, quand tu fais du mal, au fond, tu ressens du doute",
  "Depuis l’temps qu’on se noie, que notre histoire boit la tasse",
  "Deux billets de 500 brisent une amitié parce que ton ami veut plus que la moitié",
  "Ils m’ont dit qu’entre pute et pote il n’y a qu’une seule lettre",
  "Le futur improvise, le destin se débrouille",
  "Me renfermer dans l’silence, c’est mon seul repère",
  "Ce que tu racontes n’a pas de sens comme un double gode",
  "Quand vient la mort, on t’enterre sans tes milliards Est-ce que t’as déjà vu un coffre-fort à l’arrière d’un corbillard?",
  "J’ai tellement baisé la hess, sa mère, elle reviendra jamais",
  "J’suis devenu présentable depuis qu’le business est rentable",
  "La plus grande des braqueuses en vrai c’est toi, t’as tiré le gros lot en étant avec moi",
  "Tu parles des autres parce qu’on parle pas de toi",
  "Quelle vie vit-on quand on a pas la vie qu’on veut ?",
  "Avant d’redevenir poussière, on meurt à feu doux sans l’sentir",
  "J’ai tout compris mais pour eux, j’reste un incompris",
  "À la base j’ai pas d’talent, j’ai pas d’don, mais personne ne reste esclave de son destin",
  "Gims a t’il vendu son âme au diable ? Il répond !",
  "La vie ne fait aucun cadeau, le Père Noël n’existe pas dans la rue",
  "Oublie pas la chance que t’as d’pouvoir manger à table et d’avoir un sapin",
  "J’ai attendu le père Noël toute la nuit mais dans mon quartier, il est jamais venu",
  "J’t’aimerais mort parce qu’une vie n’suffit pas pour qu’j’te pardonne",
  "J’aimerais qu’mon pénis ait des yeux juste pour qu’j’puisse voir la vie en rose",
  "Si tu me trahis je t’arrache le cœur avec les mains",
  "Tu m’dis « je t’aime », j’y crois pas, ça me fait de la peine, tu te fais autant baiser que la reine des abeilles",
  "j’essaie de m’adoucir mais l’humain me rend noir",
  "Quand y’a plus d’alcool sur le sol que dans les verres, c’est qu’il est l’heure de rentrer",
  "J’ai mes plus belles étoiles là-haut, mes amis derrière les barreaux",
  "Dis-moi c’que j’dois entendre, me dis pas c’que j’veux entendre",
  "Tellement d’fils de putes qu’ont des mères irréprochables",
  "Il n’y a que les miens qui profitent de mes gains, dis à ta petite sœur de se rhabiller",
  "Me demande pas pourquoi, je répondrai parce que",
  "Tombe le masque, c’est dans l’ombre que je marche, parce qu’on me regarde pas, moi on me remarque",
  "Les rappeurs français y’en a plein que j’apprécie, mais très peu m’impressionnent",
  "Les journalistes racontent des idioties, le jet est privé et ma vie aussi",
  "44 dans la bouche, j’appuie, j’t’envoie savoir si Dieu existe",
  "J’essaie d’apprendre à la connaître mais j’comprends sa langue que quand elle suce",
  "J’donne du respect à qui m’en donne, les bons comptes font les bons amis",
  "Avoir la plus bonne, ça veut pas dire qu’t’es mignon",
  "Du sang corse comme Bonaparte, classique comme quand l’S crie « mathafack »",
  "Si tu joues la mauvaise graine, c’est à Fleury que tu vas faner",
  "Personne viendra t’sauver si t’es personne d’important",
  "Parle de la maman, j’te démarre même si t’as fait 25 ans d’boxe ou d’karaté",
  "Les flingues sont pas en plastique comme les seins d’ma feu-meu",
  "Crois-moi, l’être humain est hypocrite et ça, ça provoque beaucoup de quiproquos",
  "J’essaie d’garder la foi, je souris même quand ça va pas",
  "Je n’trouverai pas la bonne personne tant que je n’serai pas la bonne",
  "Bien sûr que je crois en Dieu mais de croire en soit c’est déjà une religion",
  "Repas sans porc, fait peur à la France plus que Monsanto",
  "Ceux qui m’sortent de la merde, je me jetterai dedans pour eux",
  "T’as écouté les gens, c’est dommage. Pourquoi revenir, c’est trop tard",
  "J’ai besoin d’tout mais j’me contente de toi",
  "Les vainqueurs l’écrivent les vaincus racontent l’histoire",
  "Y’a que quand tu baises ta daronne que j’suis de tout cœur avec toi",
  "Suffit pas d’être pour exister, suffit pas de partir pour disparaître",
  "Les grands-mères de demain, snap leur gros uc’ aujourd’hui",
  "T’as pas tourné la page; en vrai, t’as préféré changé de livre",
  "Trouver d’l’amour tout au fond d’mon cœur, c’est trouver d’l’eau dans l’plus grand des déserts",
  "Elle a soigné tous mes bobos, j’suis tombé amoureux trop tôt, et c’est trop tard pour divorcer",
  "Ils parlent de moi quand t’es avec eux, quand je suis avec eux, ils parlent de toi les envieux",
  "Relation discrète, relation parfaite Vivons cachés et on aura moins de problèmes",
  "Un mélange de haine et d’amour quand je pense à toi",
  "On reproche aux autres c’qu’on veut pas voir en soi",
  "Me donne pas ton cœur je vais l’abîmer",
  "Parfois j’ai peur d’blesser les gens, alors j’réagis lâchement",
  "Cite encore mon nom j’te fais rentrer dans ta tombe toi et ton ombre",
  "J’ai vu des mecs marrants s’prendre au sérieux plus jamais faire rire personne",
  "La justice fait semblant d’être à l’écoute Avec l’audition de Beethoven",
  "Ta pétasse écarte les jambes, elle veut qu’j’la remplisse comme le Zénith",
  "Si l’amour c’était si bien, ça s’rait interdit par la loi",
  "T’es mon reuf, j’te fais la passe, j’te lâcherai pas pour des fesses",
  "Mais si j’lui raconte nos vies je crois que j’vais rendre fou le psy",
  "J’croyais qu’il était déchiré, mon cœur est recousu, mes blessures apaisées par l’euro",
  "Dans ton cœur j’étais intermittent, tu m’as fait sortir en première mi-temps",
  "Les ients-cli sont bon qu’à revenir comme mon ex",
  "J m’arrêterai quand j’aurai plus de rides sur le front que sur les couilles",
  "J’rap pas pour que tu danses sur mon son mais sur leurs dépouilles",
  "La vérité sort d’la bouche de 6ix9ine, pas des gosses",
  "Damso confondu avec Lukaku",
  "Plutôt mourir que de coucher avec un homme. J’aurais trop peur d’aimer ça",
  "Je connais pas ré-mi-sol, la ‘sique j’m’en bats les couilles",
  "Je pense aux autres, c’est peut-être ce qui me tue",
  "La manière dont tu comptes en dit long sur ce que t’as brassé La manière dont tu pompes en dit long sur ce que t’as sucé",
  "Y a pas d’gangsters sur les réseaux sociaux, seulement des gars qu’ont du réseau",
  "J’connais pas l’rap français gros mais l’rap français me connait bien",
  "Pendant qu’les riches brûlent leur argent, les pauvres meurent à petit feu",
  "J’attrape ton boule comme les deux hémisphères",
  "Les problèmes, c’est jamais fini, quand j’en enterre un, un autre apparaît",
  "Nekfeu quitte Instagram et Twitter",
  "Aya Nakamura règle ses comptes en plein live",
  "Edouard Philippe reprend « Ah c’est Dommage » de Big Flo & Oli",
  "T’essayes de me noyer, tu m’apprends à nager",
  "Comment ça qui vivra, verra ? On est armé donc qui vivra, nous verrons",
  "Mets tes fesses sur ma face, que l’on fasse un FaceTime",
  "Leurs parents se sont saignés, dit moi où est leur éducation",
  "Aimer quelqu’un, c’est vivre avec la peur d’le perdre",
  "J’peux pas cacher tout l’mal par le bien que j’réalise",
  "Les avis c’est comme les trous de balle, tout le monde en a un",
  "Si on veut, c’est qu’on peut et quand on peut, on doit",
  "Ceux qui nous baisent n’arrivent même plus à bander",
  "Que des suceurs comme Smithers, j’m’en frotte les mains comme Monsieur Burns",
  "Les gens sont plus égocentriques qu’une chanson de Lomepal",
  "J’pense à toi à nous deux, j’vais pas bien, j’vais juste mieux",
  "Le temps est passé la marche arrière est cassée",
  "Viens dans mes bras, tu verras Ce que les autres n’ont pas",
  "C’est vrai, j’te trompe avec la bite, mon cœur, lui, n’a d’yeux que pour toi",
  "Tu préfères le raconter, moi, je préfère le vivre",
  "je vois pas tes défauts mais t’inquiètes, j’sais reconnaître les vrais des faux",
  "Personne nous a tendu la perche, aujourd’hui, ça roule en Porsche",
  "les actrices de boule en soient témoins, rien branler fait qu’éloigner la fin",
  "J’ai pas tout bien fait mais j’ai fait de mon mieux",
  "Ceux qui font les lois vivent au-dessus d’elles",
  "Je suis responsable de ce que j’écris, pas de ce que tu comprends du flow",
  "C’est moi qui créé le jeu, pas besoin de tricher",
  "Tu perds ton cœur et ton sourire. Pour guérir faut attendre",
  "vérité n’est pas bonne à dire, vaut mieux la garder pour soi, pas les faire souffrir",
  "t’as tout perdu C’tout c’que t’as gagné",
  "Je viens de la classe moyenne moyennement classe",
  "Le savoir est une arme ? Moi j’ai un flingue, j’ai pas le bac",
  "Nouveau riche, ma Lamborghini a pris quelques dos-d’ânes, j’fais ni la queue au Ritz, ni au McDonald’s",
  "La nuit j’fume et j’nous revois : T’es mon plus beau cauchemar",
  "Les âmes se taisent, les actes se font",
  "J’ai fumé des forêts de séquoia, j’étais souvent à sec, khoya",
  "Échec scolaire, j’étais d’ceux-là : aujourd’hui j’règle la note",
  "C’est pas le quartier qui me quitte, c’est moi j’quitte le quartier",
  "Si tu te coupes de tes racines, tu vas finir par faner",
  "T’es seul dans le noir, j’espère que ton ombre ne t’a pas lâché",
  "J’ai vu autant d’humanité chez les animaux Que d’animosité chez les humains",
  "J’ai des mensonges tellement beaux, tu voudras plus jamais croire la vérité",
  "Beaucoup d’adultes sont des enfants très mal éduqués",
  "J’connais ton futur, il ressemble à mon passé",
  "On a droit à une autre chance mais pas pour la même erreur",
  "Ma nouvelle copine est là que pour m’rappeler que j’pourrais jamais vraiment remplacer l’ancienne",
  "J’mens dans ta chatte comme Pinocchio",
  "Tu ne baises pas la première-fois ? Moi je ne baise pas la deuxième",
  "Une fille bien dans la maison close, une pute dans la Maison Blanche, Mélania",
  "Les hommes politiques doivent mentir sinon tu voterais pas pour eux",
  "Tu vis dans un monde où l’État peut te piller ou t’épier",
  "La bitch fait sa Françoise Hollande, je lui dis de partir, mais elle en redemande",
  "J’braque ces braqueurs, j’suis Jacques Mesrinisé ; contre le salariat, j’suis immunisé",
  "Toujours en déplacement le soir mais, c’qui compte, c’est le dépassement de soi",
  "Un remède pour chaque douleur : mélange les pilules dans un verre d’eau, putain est-ce que tu me sens ?",
  "Tu bois un verre à ma santé, et le pire c’est qu’il m’abîme le foie",
  "Avec le spliff ou dans mon lit, j’aime quand t’enlève le collant",
  "J’veux de l’or pour ma mère, j’veux du love pour moi-même, j’veux qu’tu dormes sur ma peine",
  "L’amitié, s’est fait pour faire la guerre, l’oseille, s’est fait pour acheter la paix",
  "Nique les mathématiques, ma matière préférée c’est la soie",
  "« Bonjour », je suis bien éduqué, pourtant j’ai des absences comme un député »",
  "Moi j’écrivais mes textes en classe, le temps du cours j’inversais le cours du temps",
  "Elle me dit « je t’aime », je lui réponds « je t’aime bien »",
  "Devant la juge, ça fait des 6-9 face au procureur",
  "Je suis devenu SVF, sans villa fixe",
  "Le temps est passé, les teens sont devenues des milfs",
  "J’ai dû ligoter ma peur, le manque d’argent a noirci mon cœur",
  "On voit ce qu’on veut, on veut ce qu’on voit, c’est une question de choix",
  "J’suis pas venu au monde pour rembourser des crédits",
  "Y’a pas meilleur abri que le ventre d’une mère",
  "Je n’ai confiance qu’en mon Desert Eagle et en Zizou dans les arrêts de jeu",
  "Pour passer le temps, j’achète des appartements",
  "Baba, pour ton sourire, j’donnerais ma vie et p’t-être même ma place au paradis",
  "J’connais des meufs bien qui sont même plus hlel, je connais des grosses tchoins qui sont toujours vierges",
  "Je sais que l’amour existe mais pas pour moi",
  "Finir comme eux ? J’préfère mourir",
  "La rue a fait de nous des hommes, On chasse car nos mères sont des lionnes.",
  "Les embrouilles c’est comme les joints, ça finit par se tasser",
  "Tu fais rien d’ta vie mais, tu donnes ton avis comme un mec de Twitter",
  "Une chatte après 50 ans c’est un octogone sans règle",
  "Comme les sourires de nos pères, j’deviens difficile à voir",
  "Le rap, c’est un jeu d’échecs et les fous sont toujours au plus près du roi",
  "J’regrette pas c’que j’ai perdu, j’ai trop d’amour pour c’qu’il me reste",
  "Si tu t’soucies du regard des gens, tu vas jamais y arriver",
  "J’ai pas besoin d’eux ma gueule car je sais qui je suis quand j’suis seul",
  "Ta vie, c’est d’la merde, à qui la faute? T’es figurant dans l’film de la vie d’un autre",
  "Aujourd’hui, t’es tout mais demain t’es rien",
  "Une journée sans ton affection, pour moi c’est plus long que les quatre saisons",
  "N’écoute pas les gens, c’que tu veux, tu peux l’être",
  "la violence gratuite peut coûter très cher",
  "Quand ils ont une kalash braquée sur la te-tê, les athés deviennent croyants",
  "Youssoupha en 10 Punchlines, le lyriciste Bantou",
  "À chaque tragédie, faut rester fort, c’est chacun son tour, chacun son sort",
  "Un petit fume un grand, l’âge ça veut rien dire, les p’tits veulent du respect",
  "Cette pétasse sait pas faire son lit mais dans son lit, elle sait tout faire",
  "Tu dis qu’tu vends mais tu la vends juste pour fumer",
  "Le doigt avec lequel je témoigne de ma foi c’est le même avec lequel j’peux tirer sur toi",
  "Les paysages sont désolés, pourtant les hommes n’ont pas d’excuses",
  "Si t’as pas l’niveau, ne fais pas de gosse, parents de merde donnent enfant de merde",
  "Combien de doutes avant de savoir que oui tu le peux ?",
  "On s’oublie pour ne plus s’aimer Cherche la perfection pour fuir la réalité",
  "Souvent de mauvaise humeur, noire est la couleur du cœur",
  "T’as rien compris si tu crois qu’écarter les jambes c’est ca de s’ouvrir aux autres",
  "Pardonne-moi si j’suis pas là, c’est qu’je cours derrière les milliers",
  "J’ai fait l’chien car t’es une chienne, donc les torts sont partagés",
  "Le navire coule et ils disent qu’c’est un problème de voile",
  "Peut-être que si j’ai cr que tu n’as pas, c’est que j’ai fait ce que t’as pas fait",
  "Tous ceux qui prennent de haut, j’vais leur apprendre à baisser la tête",
  "La vie t’fait voir les envieux, ils t’envient, ils t’en veulent",
  "Qui a conseillé la conseillère d’orientation?",
  "Son cul passe pas la portière, il faut une nouvelle bagnole",
  "Tu te fais baiser par qui veut la mettre",
  "J’viens à ton mariage en training, pour bien te manquer de respect",
  "Les mots sont des lames qui aiguisent haine et colère",
  "Tout ce que je prends, j’te le donne, un peu comme ma vie",
  "Nous on sait pardonner, eux ils savent pas donner",
  "J’veux être ivre, demain ne compte pas, pourquoi la vie devrait être un combat?",
  "Je l’aimais plus que moi-même, mais j’ai pas su lui montrer",
  "Le passé, c’est d’la poussière mais sache que l’passé, j’l’oublie pas",
  "J’me suis noyé dans mes rêves parce que ma vie, c’était un cauchemar",
  "Mon cœur est entouré de barbelés, l’amour m’a boycotté",
  "J’suis la craie qui grince sur le tableau, j’suis le mot dans l’dico qui vient de l’argot",
  "Nos écrans en guise de barricade, on s’envoyait des pavés",
  "Tu veux quoi ? Sauver le monde ? Bah va jouer à Fortnite La rue, ça joue pas, fais pas poukave comme l’a fait 6ix9ine",
  "C’qui tue plus dans l’monde, c’est pas la misère, c’est la jalousie",
  "Tu sais qu’une femme qui se respecte, ça vaut plus cher que de l’or",
  "Les mains dans la merde alors qu’elles sont faites pour les enterrer",
  "Cette époque est lourde, aussi lourde, que le poids qu’portent mes paupières",
  "Elle compte sur moi, je compte sur personne Je compte seulement sur mes deux mains",
  "Un toboggan au paradis, c’est la descente aux enfers",
  "J’m’en fous si ma meuf me trompe avec une autre meuf",
  "J’me défonce pour me rappeler J’me défonce pour oublier",
  "J’viens en retard comme si j’tais à l’heure",
  "Salle de prière désemplie, tous occupés à monter des empires",
  "C’est bon pour l’bénéf’ de ruiner l’Afrique, c’est bon pour l’bénéf’ d’asservir l’Asie",
  "Son absence me s’ra mortelle car sa présence m’est vitale",
  "J’sais qu’j’lui ai fait du mal Et qu’on nettoie pas ses fautes avec de l’argent sale",
  "Vous portez l’œil, moi, j’porte mes couilles",
  "Je n’aime pas les porcs à part dans un bon ragoût"
]

export default punchs